### ISSUE TITLE
specifying multiple hosts for single script doesn't seem to be working (for me)

### ISSUE THREAD

**Issue by jnahorny** [Nordstrom/ssh_exporter#18]
I've tried to do:
```
credentials:
    - host: myhost.example.com
      port: 22
      user: someuser
      keyfile: /path/to/private/key
    - host: host2.example.com
      port: 22
      user: someotheruser
      keyfile: /path/to/other/private/key
```

but this returns correct result only for last (in this case: 2nd) host. If I reorder hosts, so that 'host2.example.com` is first, and 'myhost.example.com` is below it, then the script returns correct result for 'myhost.example.com'
(I'm using HEAD of this git repo)
